services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_KEY: ${ADMIN_KEY}
      LOGGING_LEVEL_COM_AFARMS: ${LOG_LEVEL}
      INCOME_SERVICE_URL: ${INCOME_SERVICE_URL}
      EXPENSE_SERVICE_URL: ${EXPENSE_SERVICE_URL}
      INVESTMENT_SERVICE_URL: ${INVESTMENT_SERVICE_URL}
      TRANSACTION_SERVICE_URL: ${TRANSACTION_SERVICE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    env_file:
      - .env
    networks:
      - dev-network
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak-realms:/opt/keycloak/data/import/
    ports:
      - "8181:8080"
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    networks:
      - dev-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health/ready" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # PostgreSQL for Keycloak
  postgres-keycloak:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER} -d ${KEYCLOAK_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  dev-network:
    external: true
    name: dev-network

volumes:
  postgres_keycloak_data: