services:
  expense-service:
    build: .
    container_name: expense-service
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://expense-service-db:5432/expense_db
      SPRING_DATASOURCE_USERNAME: afarms
      SPRING_DATASOURCE_PASSWORD: afarms
    depends_on:
      - expense-service-db
    networks:
      - dev-network

  expense-service-db:
    image: postgres:16-alpine
    container_name: expense-service-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: afarms
      POSTGRES_PASSWORD: afarms
    volumes:
      - expense-service-db-data:/var/lib/postgresql/data
    networks:
      - dev-network

networks:
  dev-network:
    external: true
    name: dev-network

volumes:
  expense-service-db-data:
