services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: afarms
      SPRING_DATASOURCE_PASSWORD: afarms
    depends_on:
      - user-service-db
    networks:
      - dev-network

  user-service-db:
    image: postgres:16-alpine
    container_name: user-service-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: afarms
      POSTGRES_PASSWORD: afarms
    volumes:
      - user-service-db-data:/var/lib/postgresql/data
    networks:
      - dev-network

networks:
  dev-network:
    external: true
    name: dev-network

volumes:
  user-service-db-data:
