spring.application.name=income-service
server.port=${SERVER_PORT}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET}

services.user.url=${SERVICES_USER_URL}

logging.level.com.afarms.income=${LOG_LEVEL:INFO}
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

cache.user.evict-rate-ms=600000